# Generated by Django 3.1.3 on 2020-11-24 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biomaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('units', models.CharField(max_length=45)),
                ('normal_value', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('sh_dt', models.DateTimeField(auto_now=True)),
                ('del_dt', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('url', models.CharField(max_length=256)),
                ('file_type', models.CharField(max_length=45)),
                ('sh_dt', models.DateTimeField(auto_now=True)),
                ('del_dt', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=45)),
                ('complains', models.CharField(max_length=45)),
                ('diagnose', models.CharField(max_length=45)),
                ('comorbidities', models.CharField(default=None, max_length=45)),
                ('therapy_plan', models.CharField(max_length=45)),
                ('drug_prescription', models.CharField(max_length=45)),
                ('doctor_report', models.CharField(max_length=45)),
                ('doctor', models.CharField(max_length=45)),
                ('sh_dt', models.DateTimeField(auto_now=True)),
                ('del_dt', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('sh_dt', models.DateTimeField(auto_now=True)),
                ('del_dt', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=45)),
                ('date', models.DateTimeField()),
                ('sh_dt', models.DateTimeField(auto_now=True)),
                ('del_dt', models.DateTimeField(default=None)),
                ('id_protocol', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='clouddocs_app.protocol')),
                ('id_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clouddocs_app.eventtype')),
            ],
        ),
        migrations.CreateModel(
            name='EventTags',
            fields=[
                ('id_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clouddocs_app.event')),
                ('sh_dt', models.DateTimeField(auto_now=True)),
                ('del_dt', models.DateTimeField(default=None)),
                ('id_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clouddocs_app.file')),
            ],
        ),
        migrations.CreateModel(
            name='EventFiles',
            fields=[
                ('id_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clouddocs_app.event')),
                ('sh_dt', models.DateTimeField(auto_now=True)),
                ('del_dt', models.DateTimeField(default=None)),
                ('id_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clouddocs_app.file')),
            ],
        ),
        migrations.CreateModel(
            name='EventBiomaterials',
            fields=[
                ('id_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clouddocs_app.event')),
                ('sh_dt', models.DateTimeField(auto_now=True)),
                ('del_dt', models.DateTimeField(default=None)),
                ('id_biomaterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clouddocs_app.biomaterial')),
            ],
        ),
    ]
