# Generated by Django 3.1.3 on 2020-11-24 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clouddocs_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id_direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clouddocs_app.direction'),
        ),
        migrations.AlterField(
            model_name='event',
            name='id_protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clouddocs_app.protocol'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='comorbidities',
            field=models.CharField(max_length=45),
        ),
    ]
