# Generated by Django 3.1.3 on 2020-11-24 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clouddocs_app', '0002_auto_20201124_0556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtags',
            name='id_file',
        ),
        migrations.AddField(
            model_name='eventtags',
            name='id_tag',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='clouddocs_app.tag'),
        ),
    ]
