# Generated by Django 3.1.3 on 2020-11-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clouddocs_app', '0002_auto_20201124_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='del_dt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='direction',
            name='sh_dt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
