# Generated by Django 3.1.3 on 2020-11-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clouddocs_app', '0003_auto_20201124_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='del_dt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='eventbiomaterials',
            name='del_dt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='eventfiles',
            name='del_dt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='eventtags',
            name='del_dt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='del_dt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='del_dt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='del_dt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='del_dt',
            field=models.DateTimeField(null=True),
        ),
    ]
