# Generated by Django 3.1.3 on 2020-11-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clouddocs_app', '0003_auto_20201124_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
