# Generated by Django 3.1.3 on 2020-11-24 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clouddocs_app', '0004_auto_20201124_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbiomaterials',
            name='id_biomaterial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clouddocs_app.biomaterial'),
        ),
        migrations.AlterField(
            model_name='eventbiomaterials',
            name='id_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clouddocs_app.event'),
        ),
        migrations.AlterField(
            model_name='eventfiles',
            name='id_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clouddocs_app.event'),
        ),
        migrations.AlterField(
            model_name='eventfiles',
            name='id_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clouddocs_app.file'),
        ),
        migrations.AlterField(
            model_name='eventtags',
            name='id_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clouddocs_app.event'),
        ),
        migrations.AlterField(
            model_name='eventtags',
            name='id_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clouddocs_app.tag'),
        ),
    ]
