# Generated by Django 3.1.3 on 2020-11-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clouddocs_app', '0005_auto_20201124_0653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventfiles',
            name='id_event',
        ),
        migrations.RemoveField(
            model_name='eventfiles',
            name='id_file',
        ),
        migrations.RemoveField(
            model_name='eventtags',
            name='id_event',
        ),
        migrations.RemoveField(
            model_name='eventtags',
            name='id_tag',
        ),
        migrations.AddField(
            model_name='biomaterial',
            name='del_dt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='biomaterial',
            name='sh_dt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='event',
            name='biomaterials',
            field=models.ManyToManyField(to='clouddocs_app.Biomaterial'),
        ),
        migrations.AddField(
            model_name='event',
            name='files',
            field=models.ManyToManyField(to='clouddocs_app.File'),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(to='clouddocs_app.Tag'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='comorbidities',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.DeleteModel(
            name='EventBiomaterials',
        ),
        migrations.DeleteModel(
            name='EventFiles',
        ),
        migrations.DeleteModel(
            name='EventTags',
        ),
    ]
