# Generated by Django 3.1.3 on 2020-11-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clouddocs_app', '0007_auto_20201124_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='id_direction',
        ),
        migrations.AddField(
            model_name='event',
            name='directions',
            field=models.ManyToManyField(to='clouddocs_app.Direction'),
        ),
    ]
