# Generated by Django 3.1.3 on 2020-11-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clouddocs_app', '0008_auto_20201124_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='biomaterials',
        ),
        migrations.RemoveField(
            model_name='event',
            name='directions',
        ),
        migrations.RemoveField(
            model_name='event',
            name='id_protocol',
        ),
        migrations.RemoveField(
            model_name='event',
            name='id_type',
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Biomaterial',
        ),
        migrations.DeleteModel(
            name='Direction',
        ),
        migrations.DeleteModel(
            name='EventType',
        ),
        migrations.DeleteModel(
            name='Protocol',
        ),
    ]
