# Generated by Django 3.1.3 on 2020-11-25 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clouddocs_app', '0009_auto_20201125_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('sh_dt', models.DateTimeField(auto_now=True)),
                ('del_dt', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'directions',
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('sh_dt', models.DateTimeField(auto_now=True)),
                ('del_dt', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'event_types',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='direction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clouddocs_app.direction'),
        ),
        migrations.AddField(
            model_name='event',
            name='id_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clouddocs_app.eventtype'),
        ),
    ]
